-- 安全事件相关 2015-7-9 10：58
INSERT INTO `stormcenter`.`storm_auth_rule` (`name`, `title`, `type`, `status`, `condition`) VALUES ('Security/Index/index', '安全事件-首页', '1', '1', '');
INSERT INTO `stormcenter`.`storm_auth_rule` (`name`, `title`, `type`, `status`, `condition`) VALUES ('Security/Event/record', '安全事件-事件管理-事件登记', '1', '1', '');
INSERT INTO `stormcenter`.`storm_auth_rule` (`name`, `title`, `type`, `status`, `condition`) VALUES ('Security/Event/verify', '安全事件-事件管理-事件审核', '1', '1', '');
INSERT INTO `stormcenter`.`storm_auth_rule` (`name`, `title`, `type`, `status`, `condition`) VALUES ('Security/Event/trace', '安全事件-事件管理-事件跟踪', '1', '1', '');
INSERT INTO `stormcenter`.`storm_auth_rule` (`name`, `title`, `type`, `status`, `condition`) VALUES ('Security/ESearch/index', '安全事件-事件查询', '1', '1', '');
INSERT INTO `stormcenter`.`storm_auth_rule` (`name`, `title`, `type`, `status`, `condition`) VALUES ('Security/NotifyUser/index', '安全事件-系统管理-通报用户', '1', '1', '');
INSERT INTO `stormcenter`.`storm_auth_rule` (`name`, `title`, `type`, `status`, `condition`) VALUES ('Security/NotifyGroup/index', '安全事件-系统管理-通报群组', '1', '1', '');
INSERT INTO `stormcenter`.`storm_auth_rule` (`name`, `title`, `type`, `status`, `condition`) VALUES ('Security/Dic/index', '安全事件-数字字典', '1', '1', '');
INSERT INTO `stormcenter`.`storm_auth_rule` (`name`, `title`, `type`, `status`, `condition`) VALUES ('Security/Event/insert', '安全事件-事件管理-事件登记-新增', '1', '1', '');
INSERT INTO `stormcenter`.`storm_auth_rule` (`name`, `title`, `type`, `status`, `condition`) VALUES ('Security/Index/getEventOfHomeValue', '安全事件-首页-获取数据', '1', '1', '');
INSERT INTO `stormcenter`.`storm_auth_rule` (`name`, `title`, `type`, `status`, `condition`) VALUES ('Home/Image/uploadImgToServer', '图片上传', '1', '1', '');
INSERT INTO `stormcenter`.`storm_auth_rule` (`name`, `title`, `type`, `status`, `condition`) VALUES ('Security/ESearch/search', '事件查询-事件查询', '1', '1', '');
INSERT INTO `stormcenter`.`storm_auth_rule` (`name`, `title`, `type`, `status`, `condition`) VALUES ('Security/ESearch/export', '事件查询-导出表', '1', '1', '');
INSERT INTO `stormcenter`.`storm_auth_rule` (`name`, `title`, `type`, `status`, `condition`) VALUES ('Security/Event/history', '历史事件', '1', '1', '');
INSERT INTO `stormcenter`.`storm_auth_rule` (`name`, `title`, `type`, `status`, `condition`) VALUES ('Security/NotifyUser/toAdd', '安全事件-通知用户-添加用户跳转', '1', '1', '');
INSERT INTO `stormcenter`.`storm_auth_rule` (`name`, `title`, `type`, `status`, `condition`) VALUES ('Security/NotifyUser/toUpdate', '安全事件-通知用户-修改用户跳转', '1', '1', '');
INSERT INTO `stormcenter`.`storm_auth_rule` (`name`, `title`, `type`, `status`, `condition`) VALUES ('Security/NotifyUser/add', '安全事件-通知用户-添加用户', '1', '1', '');
INSERT INTO `stormcenter`.`storm_auth_rule` (`name`, `title`, `type`, `status`, `condition`) VALUES ('Security/NotifyUser/update', '安全事件-通知用户-修改用户', '1', '1', '');
INSERT INTO `stormcenter`.`storm_auth_rule` (`name`, `title`, `type`, `status`, `condition`) VALUES ('Security/NotifyUser/delete', '安全事件-通知用户-删除用户', '1', '1', '');
INSERT INTO `stormcenter`.`storm_auth_rule` (`name`, `title`, `type`, `status`, `condition`) VALUES ('Security/NotifyUser/query', '安全事件-通知用户-查询用户', '1', '1', '');
INSERT INTO `stormcenter`.`storm_auth_rule` (`name`, `title`, `type`, `status`, `condition`) VALUES ('Security/NotifyUser/beatchDelete', '安全事件-通知用户-批量删除用户', '1', '1', '');
INSERT INTO `stormcenter`.`storm_auth_rule` (`name`, `title`, `type`, `status`, `condition`) VALUES ('Security/NotifyGroup/toAdd', '安全事件-通知群组-添加群组跳转', '1', '1', '');
INSERT INTO `stormcenter`.`storm_auth_rule` (`name`, `title`, `type`, `status`, `condition`) VALUES ('Security/NotifyGroup/toUpdate', '安全事件-通知群组-修改群组跳转', '1', '1', '');
INSERT INTO `stormcenter`.`storm_auth_rule` (`name`, `title`, `type`, `status`, `condition`) VALUES ('Security/NotifyGroup/query', '安全事件-通知群组-查询群组', '1', '1', '');
INSERT INTO `stormcenter`.`storm_auth_rule` (`name`, `title`, `type`, `status`, `condition`) VALUES ('Security/NotifyGroup/queryUserGroup', '安全事件-通知群组-查询群组关联用户', '1', '1', '');
INSERT INTO `stormcenter`.`storm_auth_rule` (`name`, `title`, `type`, `status`, `condition`) VALUES ('Security/NotifyGroup/add', '安全事件-通知群组-添加群组', '1', '1', '');
INSERT INTO `stormcenter`.`storm_auth_rule` (`name`, `title`, `type`, `status`, `condition`) VALUES ('Security/NotifyGroup/update', '安全事件-通知群组-修改群组', '1', '1', '');
INSERT INTO `stormcenter`.`storm_auth_rule` (`name`, `title`, `type`, `status`, `condition`) VALUES ('Security/NotifyGroup/delete', '安全事件-通知群组-删除群组', '1', '1', '');
INSERT INTO `stormcenter`.`storm_auth_rule` (`name`, `title`, `type`, `status`, `condition`) VALUES ('Security/NotifyGroup/beatchDelete', '安全事件-通知群组-批量删除群组', '1', '1', '');
INSERT INTO `stormcenter`.`storm_auth_rule` (`name`, `title`, `type`, `status`, `condition`) VALUES ('Security/Event/query', '安全事件-事件管理-事件查询', '1', '1', '');
INSERT INTO `stormcenter`.`storm_auth_rule` (`name`, `title`, `type`, `status`, `condition`) VALUES ('Security/Event/update', '安全事件-事件管理-事件修改', '1', '1', '');
INSERT INTO `stormcenter`.`storm_auth_rule` (`name`, `title`, `type`, `status`, `condition`) VALUES ('Security/Event/beatchRepair', '安全事件-事件管理-事件批量修复', '1', '1', '');
INSERT INTO `stormcenter`.`storm_auth_rule` (`name`, `title`, `type`, `status`, `condition`) VALUES ('Security/Event/queryEventLog', '安全事件-事件管理-事件日志查询', '1', '1', '');
INSERT INTO `stormcenter`.`storm_auth_rule` (`name`, `title`, `type`, `status`, `condition`) VALUES ('Security/Event/traceView', '安全事件-事件管理-事件跟踪-详情', '1', '1', '');

-- 安全事件权限相关 2015-7-9 10：58
INSERT INTO `stormcenter`.`storm_auth_group` (`title`, `status`, `rules`, `pid`, `type`, `page_action`, `m_type`) VALUES ('安全事件管理首页', '1', '40,49', '0', '0', 'Security/Index/index', '3');
INSERT INTO `stormcenter`.`storm_auth_group` (`title`, `status`, `rules`, `pid`, `type`, `page_action`, `m_type`) VALUES ('事件管理', '1', '', '0', '0', '', '3');
INSERT INTO `stormcenter`.`storm_auth_group` (`title`, `status`, `rules`, `pid`, `type`, `page_action`, `m_type`) VALUES ('事件登记', '1', '41,48,50,53', '16', '0', 'Security/Event/record', '3');
INSERT INTO `stormcenter`.`storm_auth_group` (`title`, `status`, `rules`, `pid`, `type`, `page_action`, `m_type`) VALUES ('事件审核', '1', '42,69,70', '16', '0', 'Security/Event/verify', '3');
INSERT INTO `stormcenter`.`storm_auth_group` (`title`, `status`, `rules`, `pid`, `type`, `page_action`, `m_type`) VALUES ('事件跟踪', '1', '43,71,70,69,73', '16', '0', 'Security/Event/trace', '3');
INSERT INTO `stormcenter`.`storm_auth_group` (`title`, `status`, `rules`, `pid`, `type`, `page_action`, `m_type`) VALUES ('事件查询', '1', '44,51,52', '0', '0', 'Security/ESearch/index', '3');
INSERT INTO `stormcenter`.`storm_auth_group` (`title`, `status`, `rules`, `pid`, `type`, `page_action`, `m_type`) VALUES ('系统管理', '1', '', '0', '0', '', '3');
INSERT INTO `stormcenter`.`storm_auth_group` (`title`, `status`, `rules`, `pid`, `type`, `page_action`, `m_type`) VALUES ('通报用户', '1', '45,54,55,58,59,60', '21', '0', 'Security/NotifyUser/index', '3');
INSERT INTO `stormcenter`.`storm_auth_group` (`title`, `status`, `rules`, `pid`, `type`, `page_action`, `m_type`) VALUES ('通报群组', '1', '46,61,62,63,67,68', '21', '0', 'Security/NotifyGroup/index', '3');
INSERT INTO `stormcenter`.`storm_auth_group` (`title`, `status`, `rules`, `pid`, `type`, `page_action`, `m_type`) VALUES ('数字字典', '1', '47', '21', '0', 'Security/Dic/index', '3');
INSERT INTO `stormcenter`.`storm_auth_group` (`title`, `status`, `rules`, `pid`, `type`, `page_action`, `m_type`) VALUES ('通报用户-添加用户', '1', '54,56', '22', '0', 'Security/NotifyUser/toAdd', '3');
INSERT INTO `stormcenter`.`storm_auth_group` (`title`, `status`, `rules`, `pid`, `type`, `page_action`, `m_type`) VALUES ('通报用户-修改用户', '1', '55,57', '22', '0', 'Security/NotifyUser/toUpdate', '3');
INSERT INTO `stormcenter`.`storm_auth_group` (`title`, `status`, `rules`, `pid`, `type`, `page_action`, `m_type`) VALUES ('通报群组-添加群组', '1', '61,65', '23', '0', 'Security/NotifyGroup/toAdd', '3');
INSERT INTO `stormcenter`.`storm_auth_group` (`title`, `status`, `rules`, `pid`, `type`, `page_action`, `m_type`) VALUES ('通报群组-修改群组', '1', '62,66', '23', '0', 'Security/NotifyGroup/toUpdate', '3');
INSERT INTO `stormcenter`.`storm_auth_group` (`title`, `status`, `rules`, `pid`, `type`, `page_action`, `m_type`) VALUES ('事件跟踪-详情', '1', '73,69,72', '19', '0', 'Security/Event/traceView', '3');
